site_name: "OTEAPI DLite"
site_description: Documentation for the OTEAPI DLite package
site_url: https://EMMC-ASBL.github.io/oteapi-dlite
copyright: Copyright &copy; 2022 SINTEF

theme:
  name: material
  palette:
    scheme: default
    primary: purple
    accent: amber
  icon:
    repo: fontawesome/brands/github
  logo: material/library-shelves
  favicon: assets/images/favicon.png
  language: en
  # features:
  #   - navigation.instant
  #   - navigation.top

repo_name: "oteapi-dlite"
repo_url: "https://github.com/EMMC-ASBL/oteapi-dlite"
edit_uri: ""

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/EMMC-ASBL
      name: "EMMC-ASBL on GitHub"
  version:
    provider: mike
    default: latest

extra_css:
  - css/reference.css

markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.tabbed
  - pymdownx.caret
  - pymdownx.tilde
  - pymdownx.keys
  - pymdownx.snippets
  - toc:
      permalink: true

plugins:
  - search:
      lang: en
  - mkdocstrings:
      default_handler: python
      enable_inventory: true
      handlers:
        python:
          options:
            # General options
            show_source: true
            show_bases: true

            # Heading options
            heading_level: 2
            show_root_heading: false
            show_root_toc_entry: true
            show_root_full_path: true
            show_object_full_path: false
            show_category_heading: false

            # Members options
            members: null
            inherited_members: false
            filters:
              - "!^_"
              - "^__init__$"
              - "!__json_encoder__$"
              - "!__all__$"
              - "!__config__$"
              - "!__str__$"
              - "!__repr__$"
            group_by_category: true

            # Docstring options
            docstring_style: google
            docstring_options:
              replace_admonitions: true
            show_if_no_docstring: false
  - awesome-pages
  - autorefs:
      resolve_closest: true

watch:
  - oteapi_dlite
