[build-system]
requires = [
    "setuptools>=42",
    "wheel"
]
build-backend = "setuptools.build_meta"

dependencies = [
    "DLite-Python>=0.3.3,<1",
    "numpy>=1.21,<2",
    "oteapi-core>=0.1.2",
    "Pillow>=9.0.1,<11",
    "psycopg2-binary!=2.9.6",
    "tripper>=0.1.2",
]

[project.optional-dependencies]
dev = [
    "otelib~=0.3",
    "pre-commit~=3.3",
    "pylint~=2.17",
    "pytest~=7.4",
    "pytest-cov~=4.1",
    "pyyaml>=5.0",  # docker-compose requires PyYAML<6,>=3.10
]
docs = [
     "invoke~=2.2",
     "mike~=1.1",
     "mkdocs~=1.5",
     "mkdocs-awesome-pages-plugin~=2.9",
     "mkdocs-material~=9.1",
     "mkdocstrings[python]~=0.22.0",
]

[tool.mypy]
python_version = "3.9"
ignore_missing_imports = true
scripts_are_modules = true
warn_unused_configs = true
show_error_codes = true
allow_redefinition = true

[tool.pylint.messages_control]
max-line-length = 80
disable = [
    "duplicate-code",
    "no-name-in-module",
    "too-few-public-methods",
    "no-self-argument",
    "invalid-name",
]

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-rs --cov=oteapi_dlite --cov-report=term --durations=10"
filterwarnings = [
    "ignore:.*imp module.*:DeprecationWarning",
    "ignore:.*_yaml extension module.*:DeprecationWarning"
]
