[build-system]
requires = [
    "setuptools>=42",
    "wheel"
]
build-backend = "setuptools.build_meta"

[tool.black]
line-length = 80

[tool.mypy]
python_version = "3.9"
ignore_missing_imports = true
scripts_are_modules = true
warn_unused_configs = true
show_error_codes = true
allow_redefinition = true

[tool.pylint.messages_control]
max-line-length = 80
disable = [
    "duplicate-code",
    "no-name-in-module",
    "too-few-public-methods",
    "no-self-argument",
    "invalid-name",
    # pylint thinks all pydantic model instance attributes are FieldInfo.
    # This is wrong, and it's a known issue.
    "no-member",
]

[tool.pytest.ini_options]
addopts = "-rs --cov=oteapi_dlite --cov-report=term-missing"
filterwarnings = []
