name: CI/CD - New updates to 'master'

on:
  push:
    branches: [master]

jobs:
  update-deps-branch-and-docs:
    name: External
    uses: SINTEF/ci-cd/.github/workflows/ci_cd_updated_default_branch.yml@v2.9.2
    if: github.repository_owner == 'EMMC-ASBL'
    with:
      # General
      git_username: "${{ vars.CI_CD_GIT_USER }}"
      git_email: "${{ vars.CI_CD_GIT_EMAIL }}"
      default_repo_branch: master

      # Permanent dependencies branch
      update_dependencies_branch: false

      # Build & publish documentation
      update_docs: true
      update_python_api_ref: true
      package_dirs: oteapi_dlite
      update_docs_landing_page: true
      python_version: "3.10"
      doc_extras: "[docs]"
      changelog_exclude_labels: "skip_changelog,duplicate,question,invalid,wontfix"
      docs_framework: mkdocs
      full_docs_dirs: |
        models
        strategies
      landing_page_replacements: |
        (LICENSE),(LICENSE.md)
        https://EMMC-ASBL.github.io/oteapi-dlite/latest/,
        all_strategies),all_strategies.md)

    secrets:
      PAT: ${{ secrets.RELEASE_PAT }}
